POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IldpbGx5IFdvbmthIiwiaWQiOiI2MTQ3MzNhMTFmYjVlYjM3YTQ0ZGE0ZTEiLCJpYXQiOjE2MzIwNjY1ODN9.AneuGa5egIOOafIXXa40o2EPj5GOuFzDWkx4fLWXvPs

{
    "title": "Me ollaan jo eellä",
    "author": "Ammattimies",
    "url": "www.rugby.fi",
    "likes": 10
}